import { COLOR_FIELD_NAMES, SHADOW_SLOTS } from '../types';
import type { ThemeJson, ThemeJsonShadow } from '../types';

/// G3 — emit a drop-in `theme.dart` from the [ThemeJson] source of truth (spec
/// §3, §4.4). Two `const FwTokens` (light + dark) against the §5 contract, with
/// shared `_radii`/`_shadows`/`_type` consts (identical across brightness, as in
/// every tweakcn export). The Dart is a **pure function of the JSON** — `emitDart`
/// reads every schema field, which the S3 totality test pins.

/// Minimal Dart numeric literal: integers stay integral (`16`, `-1`), fractions
/// keep their decimals (`0.5`), `-0` normalizes to `0`. Dart accepts an integer
/// literal wherever a `double` is expected, matching the engine's own style.
function num(n: number): string {
  return Object.is(n, -0) ? '0' : String(n);
}

/// `Color(0xAARRGGBB)` from an `AARRGGBB` hex string.
function color(hex: string): string {
  return `Color(0x${hex})`;
}

/// One `BoxShadow(...)`. `color` and `offset` are always emitted; `blurRadius`
/// and `spreadRadius` only when non-zero (matching the engine's defaults so a
/// blur-/spread-less shadow reads identically to a hand-written one).
function boxShadow(l: ThemeJsonShadow): string {
  const parts = [`color: ${color(l.color)}`, `offset: Offset(${num(l.x)}, ${num(l.y)})`];
  if (l.blur !== 0) parts.push(`blurRadius: ${num(l.blur)}`);
  if (l.spread !== 0) parts.push(`spreadRadius: ${num(l.spread)}`);
  return `BoxShadow(${parts.join(', ')})`;
}

function shadowsConst(json: ThemeJson): string {
  const slots = SHADOW_SLOTS.map(({ slot }) => {
    const layers = json.shadows[slot].map((l) => `    ${boxShadow(l)},`).join('\n');
    return `  ${slot}: <BoxShadow>[\n${layers}\n  ],`;
  }).join('\n');
  return `const FwShadows _shadows = FwShadows(\n${slots}\n);`;
}

function typographyConst(json: ThemeJson): string {
  const t = json.typography;
  const parts = [`sans: '${t.sans}'`, `serif: '${t.serif}'`, `mono: '${t.mono}'`];
  // `tracking` defaults to 0 in FwTypographyTheme; emit only when meaningful.
  if (t.tracking !== 0) parts.push(`tracking: ${num(t.tracking)}`);
  return `const FwTypographyTheme _type = FwTypographyTheme(\n  ${parts.join(',\n  ')},\n);`;
}

function radiiConst(json: ThemeJson): string {
  const r = json.radii;
  return (
    `const FwRadii _radii = FwRadii(base: ${num(r.base)}, sm: ${num(r.sm)}, ` +
    `md: ${num(r.md)}, lg: ${num(r.lg)}, xl: ${num(r.xl)});`
  );
}

function colorsConst(colors: Readonly<Record<string, string>>): string {
  const fields = COLOR_FIELD_NAMES.map((f) => `    ${f}: ${color(colors[f])},`).join('\n');
  return `  colors: FwColors(\n${fields}\n  ),`;
}

function tokensConst(name: string, json: ThemeJson, colors: Readonly<Record<string, string>>): string {
  return (
    `const FwTokens ${name} = FwTokens(\n` +
    `  radiusBase: ${num(json.radiusBase)},\n` +
    `  radii: _radii,\n` +
    `  shadows: _shadows,\n` +
    `  typography: _type,\n` +
    `${colorsConst(colors)}\n` +
    `);`
  );
}

/// The file header: provenance + the font-wiring stub + a full account of every
/// dropped/defaulted token (spec §4.3/§7.4 — nothing silent).
function header(json: ThemeJson): string {
  const t = json.typography;
  const lines = [
    '// GENERATED by the flutterwindcss tweakcn → theme.dart generator.',
    '// Do not edit by hand — re-run the generator to regenerate.',
    `// Conversion: ${json.meta.conversion}.`,
    '//',
    `// Fonts named by this theme: ${t.sans} (sans), ${t.serif} (serif), ${t.mono} (mono).`,
    '// flutterwindcss bundles no fonts — the names round-trip, but you must wire',
    '// them yourself (or Flutter falls back to the platform family):',
    '//   // TODO: add `google_fonts` to your pubspec and apply these families on',
    '//   // FwTheme, or bundle the font files and declare them in pubspec.yaml.',
  ];
  if (json.meta.droppedVars.length > 0) {
    lines.push('//', `// Dropped unknown CSS vars: ${json.meta.droppedVars.join(', ')}.`);
  }
  if (json.meta.notes.length > 0) {
    lines.push('//', '// Defaulted / dropped tokens:');
    for (const note of json.meta.notes) lines.push(`//   - ${note}`);
  }
  return lines.join('\n');
}

/// Emit the complete `theme.dart` source for a [ThemeJson].
export function emitDart(json: ThemeJson): string {
  return [
    header(json),
    '',
    "import 'package:flutter/painting.dart';",
    "import 'package:flutterwindcss/flutterwindcss.dart';",
    '',
    radiiConst(json),
    '',
    typographyConst(json),
    '',
    shadowsConst(json),
    '',
    tokensConst('lightTheme', json, json.colors.light),
    '',
    tokensConst('darkTheme', json, json.colors.dark),
    '',
  ].join('\n');
}
