// tooling/bake_palette.dart
// Transcribes tooling/palette/tailwind_v4_palette.json into a Dart source file
// of `const Color`s. No color math — pure hex → ARGB transcription.
import 'dart:convert';
import 'dart:io';

void main() {
  final jsonFile = File('tooling/palette/tailwind_v4_palette.json');
  final data = jsonDecode(jsonFile.readAsStringSync()) as Map<String, dynamic>;

  final b = StringBuffer()
    ..writeln('// GENERATED by tooling/bake_palette.dart — do not edit by hand.')
    ..writeln('// Source: tooling/palette/tailwind_v4_palette.json (Tailwind v4).')
    ..writeln("import 'dart:ui' show Color;")
    ..writeln()
    ..writeln("/// Baked Tailwind v4 palette swatches, keyed `hue-shade` (e.g. `blue-500`).")
    ..writeln("/// Single-tone entries (`black`, `white`) are keyed by name.")
    ..writeln('const Map<String, Color> fwBakedPalette = <String, Color>{');

  data.forEach((hue, value) {
    if (value is String) {
      b.writeln("  '$hue': ${_color(value)},");
    } else {
      (value as Map<String, dynamic>).forEach((shade, hex) {
        b.writeln("  '$hue-$shade': ${_color(hex as String)},");
      });
    }
  });
  b.writeln('};');

  File('packages/flutterwindcss/lib/src/tokens/palette.g.dart')
      .writeAsStringSync(b.toString());
  stdout.writeln('Wrote palette.g.dart (${data.length} hue groups).');
}

String _color(String hex) {
  final h = hex.replaceFirst('#', '');
  final argb = 0xFF000000 | int.parse(h, radix: 16);
  return 'Color(0x${argb.toRadixString(16).toUpperCase().padLeft(8, '0')})';
}
